### ISSUE TITLE
Incorrect data in spreadsheet

### ISSUE THREAD

**Issue by kakaroto** [MrPrimate/ddb-meta-data#9]
Hello!

someone reported to me that the [spreadsheet](https://docs.google.com/spreadsheets/d/17b4jG2W521N_nFkE1jr2UGEjixHGjHGnEO9eSKhFmwo/edit#gid=190854504) was reporting that walls existed for some maps from BGDIA but the converted book didn't have walls.
Checking the spreadsheet, it feels like there's a copy/paste error since a lot of the entries have the exact same numbers of 25 walls, 14 lights, 10 pins, 10 actors, and 8 drawings, especially noticeable as you scroll through the entire list of rows.
![image](https://github.com/MrPrimate/ddb-meta-data/assets/27990/4119ab7b-4328-47c8-86be-f748a3dd1995)

I'm not sure if those are generated by a script you have on the backend, but it likely has a bug in that case. If you're not using a script, then it's likely a copy/paste error, and it should be possible to parse the jsons to determine how many walls/lights/tokens/pins/drawings there are in each scene and update all the values in the spreadsheet accordingly.
Thanks!

**Comment by MrPrimate** [comment]
The spreadsheet is done when people submit scenes through the form. All the links should have been replaced to point to https://docs.ddb.mrprimate.co.uk/status.html which uses data from the repo and is built on a new release

**Comment by kakaroto** [comment]
Ah thanks! I did know about the status page, but forgot about it.
Thanks for updating the README as well. I'll do that on our side.

Also, I figured out why BGDIA didn't have walls (the metadata/status page does have walls for those scenes).
The metadata walls are missing an `_id` field on every wall, so they all become invalid/deleted when launching Foundry v11. Solution is for the user to launch in v10 first (which will add the `_id` fields) before migrating it to v11. I don't know if you do it in your adventure muncher, but we'll be generating random ids for all embedded entities from now on during conversion, to avoid the issue with v11 leveldb migration.

**Comment by MrPrimate** [comment]
The importer imports a generated document, so I suspect Foundry does some conversion for us

**Comment by kakaroto** [comment]
> The importer imports a generated document, so I suspect Foundry does some conversion for us

ok, not sure then, there might be an issue you're not aware of then cause v11 doesn't do the conversion properly. You may want to test it out at least and confirm.
We just filed an issue for it here: https://github.com/foundryvtt/foundryvtt/issues/9969
I assume it will be fixed in an upcoming release, but for now we're going to be generated the random ids on our side before v11 sees it.
I hope it helps!
